### ISSUE TITLE
Microsoft Flow examples

### ISSUE THREAD

**Issue by johnnliu** [microsoftgraph/msgraph-community-samples#7]
## Category
- [ ] Typo
- [ ] Bug
- [x] Additional sample request / idea

## Submission Guidelines

> - All suggestions or bugs are welcome, please let us know what's on your mind.

I want to submit two Microsoft Flow examples, how would we host this?  I can do:

* exported ZIP files x2
* exported JSON definition files x2
* explanation read-me

The two Flows would be 1.  subscribe to a graph webhook for groups, and a second Flow is a listener.  Combined, these creates a brand new type of trigger for Microsoft Flow.

## export zip files

This is better for re-import into Flow.  But difficult to maintain as it's a zipped file of lots of ... files.

## export JSON

This isn't easily importable back into Flow, this is suitable for LogicApps.  

Easier to maintain, as it is just one JSON file.

**Comment by andrewconnell** [comment]
Closing due to no action required...
